export interface StockListItem {
  symbol: string;
  name: string;
  sector: string;
  country: string;
  countryCode: string;
  exchange: string;
  price: number;
  changePercent: number;
  trend: 'up' | 'down';
}

export const MOCK_STOCKS: StockListItem[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    sector: 'Technology',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 193.42,
    changePercent: 1.24,
    trend: 'up',
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    sector: 'Technology',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 412.18,
    changePercent: -0.67,
    trend: 'down',
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    sector: 'Technology',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 141.62,
    changePercent: 0.88,
    trend: 'up',
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    sector: 'Consumer Discretionary',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 156.44,
    changePercent: -1.05,
    trend: 'down',
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    sector: 'Semiconductors',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 588.9,
    changePercent: 2.91,
    trend: 'up',
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    sector: 'Automobiles',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 238.71,
    changePercent: -1.34,
    trend: 'down',
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    sector: 'Technology',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 361.05,
    changePercent: 1.12,
    trend: 'up',
  },
  {
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    sector: 'Communication Services',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 492.88,
    changePercent: 0.54,
    trend: 'up',
  },
  {
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    sector: 'Technology',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 604.32,
    changePercent: -0.89,
    trend: 'down',
  },
  {
    symbol: 'INTC',
    name: 'Intel Corp.',
    sector: 'Semiconductors',
    country: 'USA',
    countryCode: 'US',
    exchange: 'NASDAQ',
    price: 43.18,
    changePercent: 0.41,
    trend: 'up',
  },

  // ===== NON-USA =====

  {
    symbol: '7203.T',
    name: 'Toyota Motor Corp.',
    sector: 'Automobiles',
    country: 'Japan',
    countryCode: 'JP',
    exchange: 'TSE',
    price: 18.72,
    changePercent: 0.62,
    trend: 'up',
  },
  {
    symbol: 'BMW.DE',
    name: 'BMW AG',
    sector: 'Automobiles',
    country: 'Germany',
    countryCode: 'DE',
    exchange: 'XETRA',
    price: 102.44,
    changePercent: -0.78,
    trend: 'down',
  },
  {
    symbol: 'SIE.DE',
    name: 'Siemens AG',
    sector: 'Industrial Conglomerates',
    country: 'Germany',
    countryCode: 'DE',
    exchange: 'XETRA',
    price: 171.8,
    changePercent: 0.95,
    trend: 'up',
  },
  {
    symbol: 'VOW3.DE',
    name: 'Volkswagen AG',
    sector: 'Automobiles',
    country: 'Germany',
    countryCode: 'DE',
    exchange: 'XETRA',
    price: 121.33,
    changePercent: -1.21,
    trend: 'down',
  },
  {
    symbol: 'RY.TO',
    name: 'Royal Bank of Canada',
    sector: 'Financial Services',
    country: 'Canada',
    countryCode: 'CA',
    exchange: 'TSX',
    price: 132.56,
    changePercent: 0.36,
    trend: 'up',
  },
  {
    symbol: 'BNS.TO',
    name: 'Bank of Nova Scotia',
    sector: 'Financial Services',
    country: 'Canada',
    countryCode: 'CA',
    exchange: 'TSX',
    price: 63.41,
    changePercent: -0.52,
    trend: 'down',
  },
  {
    symbol: 'NESN.SW',
    name: 'Nestlé SA',
    sector: 'Consumer Staples',
    country: 'Switzerland',
    countryCode: 'CH',
    exchange: 'SIX',
    price: 98.44,
    changePercent: 0.38,
    trend: 'up',
  },
  {
    symbol: 'HSBA.L',
    name: 'HSBC Holdings',
    sector: 'Financial Services',
    country: 'UK',
    countryCode: 'GB',
    exchange: 'LSE',
    price: 6.52,
    changePercent: -0.44,
    trend: 'down',
  },
  {
    symbol: 'BP.L',
    name: 'BP PLC',
    sector: 'Energy',
    country: 'UK',
    countryCode: 'GB',
    exchange: 'LSE',
    price: 5.11,
    changePercent: 0.71,
    trend: 'up',
  },
  {
    symbol: 'TCS.NS',
    name: 'Tata Consultancy Services',
    sector: 'IT Services',
    country: 'India',
    countryCode: 'IN',
    exchange: 'NSE',
    price: 41.88,
    changePercent: -0.33,
    trend: 'down',
  },
];
